project_id = "aezvouallinpwtuaakes"

[functions.create-payment]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.get-booked-slots]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.send-email]
verify_jwt = false

