// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ootdiuulgnwijkctbabi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vdGRpdXVsZ253aWprY3RiYWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzE2NzYsImV4cCI6MjA2ODg0NzY3Nn0.2k8QIqkygtG1-FHIo-aG5YsqBJRUKAomjjbwEj1qNog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});